/** Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.**/

var x = 0;
var y = 1; 
var sum = 0;

for(var z = x + y; z < 4000000; z = x + y) { 
	x = y;
	y = z;
	if (z % 2 === 0){
		sum += z;
	}
}

console.log("The sum of Fibonacci sequence terms which are even and less in value than 4,000,000 is " + sum);